/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neptune_api_Recognize */

#ifndef _Included_com_neptune_api_Recognize
#define _Included_com_neptune_api_Recognize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neptune_api_Recognize
 * Method:    recognize
 * Signature: ([F)I
 */
JNIEXPORT jint JNICALL Java_com_neptune_api_Recognize_recognize
  (JNIEnv *, jclass, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
