/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neptune_api_Grab */

#ifndef _Included_com_neptune_api_Grab
#define _Included_com_neptune_api_Grab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neptune_api_Grab
 * Method:    capture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_neptune_api_Grab_capture
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
