/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neptune_api_Analyze */

#ifndef _Included_com_neptune_api_Analyze
#define _Included_com_neptune_api_Analyze
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neptune_api_Analyze
 * Method:    analyze
 * Signature: (Ljava/util/List;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_neptune_api_Analyze_analyze
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
