/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neptune_api_Facerig */

#ifndef _Included_com_neptune_api_Facerig
#define _Included_com_neptune_api_Facerig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neptune_api_Facerig
 * Method:    facerig
 * Signature: (Lcom/neptune/config/analyze/CaculateInfo;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_neptune_api_Facerig_facerig
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
